CREATE TABLE book (
	id VARCHAR(100) NOT NULL,
	title VARCHAR(100) NOT NULL,
	author VARCHAR(100) NOT NULL,
	language VARCHAR(100) NOT NULL,
	synopsis VARCHAR(255),
	total_page INT NOT NULL,
	current_page INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);